sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t jiangren-demo -f Dockerfile.dev .

script:
  - docker run -e CI=true jiangren-demo npm run test -- --coverage

deploy:
  #specify the provider 
  provider: elasticbeanstalk
  #specify the region where the provider is present, You can get this from the AWS ElasticBeanstalk dashboard
  region: "ap-southeast-2"
  #Specify the application name in AWS elastic beanstalk
  app: "jiangren-demo"
  #Specify the environment name in AWS elastic beanstalk
  env: "JiangrenDemo-env"
  #Specify the Bucket name which is the name of the S3 (storage) which is created as part of Elastic beanstalk in AWS
  bucket_name: "elasticbeanstalk-ap-southeast-2-782233832006"
  #specify the path of the Bucket , this will be similar to the App name above
  bucket_path: "jiangren-demo"
  #specify when you want to deploy (we want to deploy only when we push code to master branch)
  on:
    branch: master
  #Specify the Environment variable name from which Travis can get the ACCESS_KEY to AWS
  access_key_id: $AWS_ACCESS_KEY
  #Specify the Environment variable name from which Travis can get the SECRET_KEY to AWS
  secret_access_key: $AWS_SECRET_KEY
  edge: true