sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t jiangren-demo -f Dockerfile.dev .

script:
  - docker run -e CI=true jiangren-demo npm run test -- --coverage